timezone: America/New_York
title: Van Life with Pets
description: Permaculture VanDwelling
baseurl: ''
url: 'https://vanlifewithpets.annalisagross.com'
author-name: Anna Lisa Gross
author-image: profile_.jpg
author-job: Permaculture VanDwelling
author-email: null
author-twitter: annalisa144
about-author: >-
  Anna Lisa &#38; Phillip lived in their van with three dogs and two cats in
  the mountains of central Mexico for a year. <a
  href="https://reverdecer.annalisagross.com/">View permaculture adVantures.</a>
  Now they're traveling with fewer pets; rodents and bugs still hitchhike.
social-twitter: annalisa144
social-facebook: annalisa.gross.5
social-github: annalisa144
social-pinterest: null
social-instagram: annalisamexico
social-youtube: indiana144
social-vk: null
social-linkedin: null
social-tumblr: annalisa144
rss: ''
mailchimp: null
google-analytics: null
markdown: kramdown
permalink: '/:year/:month/:day/:title/'
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-figure
paginate: 7
paginate_path: '/page/:num/'
include:
  - _pages
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
future: false
defaults:
  - scope:
      path: ''
      type: posts
    values:
      date: '2099-01-01 07:00:00 -0500'
      image: ''
      tags: ''
      categories: ''
      layout: post
repository: phillipzink/vanlifewithpets
